### ISSUE TITLE
Want to add "two sum" in python 

### ISSUE THREAD

**Issue by kaif2305** [Kapoor-0905/Hacktoberfest-2022#10]

**Comment by Kapoor-0905** [comment]
Sure you can add it 
do star and fork the repo

**Comment by paras3624** [comment]
Hey. I would like to contribute to this issue.

**Comment by Kapoor-0905** [comment]
> Hey. I would like to contribute to this issue.

Sure you can contribute 
Do star and fork the repo

**Comment by Shubham2816** [comment]
pls i m new here and not able to make pull request how u want if there is any video pls let me know pls

**Comment by Kapoor-0905** [comment]
https://www.youtube.com/watch?v=RGOj5yH7evk
[https://www.bing.com/th?id=OVP.P4hUF8UQMCjJjcNkS814ogHgFo&pid=Api]<https://www.youtube.com/watch?v=RGOj5yH7evk>
Git and GitHub for Beginners - Crash Course<https://www.youtube.com/watch?v=RGOj5yH7evk>
Learn about Git and GitHub in this tutorial. These are important tools for all developers to understand. Git and GitHub make it easier to manage different software versions and make it easier for multiple people to work on the same software project. This course was developed by Gwen Faraday. Check out her YouTube channel: https://www.youtube.com/channel/UCxA99Yr6P_tZF9_BgtMGAWA 🔗 Git Commands: https://gist.github.com/gwenf/19e5748a5391929e8e938a22c8a4b3f2 🔗 Install git:...
www.youtube.com

________________________________
