### ISSUE TITLE
Want to add "Sudoku Solver" program in JAVA

### ISSUE THREAD

**Issue by Aman-kulshreshtha** [Kapoor-0905/Hacktoberfest-2022#19]
I want to add a program that takes a 9x9  incomplete sudoku and prints a solution to it if possible

**Comment by Aman-kulshreshtha** [comment]
please assign this to me
@Kapoor-0905

**Comment by Kapoor-0905** [comment]
> please assign this to me @Kapoor-0905

Assigned 👍🏻 
do star and fork the repo
