### ISSUE TITLE
want to add code for "Josephus problem" in JAVA

### ISSUE THREAD

**Issue by Aman-kulshreshtha** [Kapoor-0905/Hacktoberfest-2022#20]
I wish to add the solution code for Josephus problem in java....please assign this to me @Kapoor-0905

**Comment by Kapoor-0905** [comment]
Assigned 👍🏻

**Comment by Shubham2816** [comment]
I want to add the solution for the JOSEPHUS problem in java ... so please assign me this  @Kapoor-0905
